Add support for compilation of protos into Java library
Hydrospheredata/hydro-serving-protos pull request #42
Opened 2019-12-25 15:54 UTC by tidylobster

2019-12-25 15:55 UTC, tidylobster commented
Need to add scripts for publishing a compiled java library.

2020-07-02 08:12 UTC, KineticCookie requested changes
Need to pass secrets from jenkins and test release.

Previously, we deployed it manually due to some errors.

2021-09-09 10:37 UTC, KineticCookie submitted a review, later dismissed

2021-09-09 10:38 UTC, KineticCookie reviewed
Need to pass creds and package version

2021-09-10 12:44 UTC, akastav approved these changes

2021-09-11 06:00 UTC, merged